apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-ontap-secret
type: Opaque
stringData:
  username: vsadmin
  password: netapp123!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas
spec:
  version: 1
  storageDriverName: ontap-nas
  managementLIF: 172.28.4.74
  backendName: tbc-ontap-nas
  exportPolicy: default
  storagePrefix: "devocp002_"
  autoExportPolicy: true
  autoExportCIDRs: ['172.28.11.0/24']
  credentials:
    name: backend-tbc-ontap-secret
